exports.messages = {
    allContentUnblocked: "all-content-unblocked",
    contentBlocked: "content-blocked",
    disableRawView: "disable-raw-view",
    enableRawView: "enable-raw-view",
    fileOpen: "file-open",
    finishLoad: "finish-load",
    leaveRawText: "leave-raw-text",
    openFile: "open-file",
    openFileInNewWindow: "open-file-in-new-window",
    openInternal: "open-internal",
    openInternalInNewWindow: "open-internal-in-new-window",
    prepareReload: "prepare-reload",
    reloadPrepared: "reload-prepared",
    resetContentBlocking: "reset-content-blocking",
    restorePosition: "restore-position",
    unblockAll: "unblock-all",
    unblockURL: "unblock-url",
    viewRawText: "view-raw-text",
}
