name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    if: github.actor == github.repository_owner
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Rebuild Electron
        run: npm rebuild electron
      - name: Test
        run: npm run test-all
