name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Install Electron
        run: npx install-electron
      - name: Run Electron to force download
        run: npx electron --version
      - name: Test
        run: npm run test-all
